export const SAVE_USER = 'SAVE_USER'
export const ADD_TODO = 'ADD_TODO'
export const LOAD_ALL_TODOS = 'LOAD_ALL_TODOS'
export const LOAD_ALL_TASKS = 'LOAD_ALL_TASKS'
export const UPDATE_TASK = 'UPDATE_TASK'
export const GET_TODO = 'UPDATE_TASK'